// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: serialization.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Basic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id         int32               `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ServiceIds []uint32            `protobuf:"varint,3,rep,packed,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	Additional []*Basic_Additional `protobuf:"bytes,4,rep,name=additional,proto3" json:"additional,omitempty"`
	Dict       map[string]float32  `protobuf:"bytes,5,rep,name=dict,proto3" json:"dict,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
}

func (x *Basic) Reset() {
	*x = Basic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basic) ProtoMessage() {}

func (x *Basic) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basic.ProtoReflect.Descriptor instead.
func (*Basic) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{0}
}

func (x *Basic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Basic) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Basic) GetServiceIds() []uint32 {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *Basic) GetAdditional() []*Basic_Additional {
	if x != nil {
		return x.Additional
	}
	return nil
}

func (x *Basic) GetDict() map[string]float32 {
	if x != nil {
		return x.Dict
	}
	return nil
}

type Basic_Additional struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Strs []string `protobuf:"bytes,2,rep,name=strs,proto3" json:"strs,omitempty"`
}

func (x *Basic_Additional) Reset() {
	*x = Basic_Additional{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Basic_Additional) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basic_Additional) ProtoMessage() {}

func (x *Basic_Additional) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basic_Additional.ProtoReflect.Descriptor instead.
func (*Basic_Additional) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Basic_Additional) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Basic_Additional) GetStrs() []string {
	if x != nil {
		return x.Strs
	}
	return nil
}

var File_serialization_proto protoreflect.FileDescriptor

var file_serialization_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a, 0x05, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x0a, 0x61, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x44, 0x69,
	0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x69, 0x63, 0x74, 0x1a, 0x32, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x72,
	0x73, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x69, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_serialization_proto_rawDescOnce sync.Once
	file_serialization_proto_rawDescData = file_serialization_proto_rawDesc
)

func file_serialization_proto_rawDescGZIP() []byte {
	file_serialization_proto_rawDescOnce.Do(func() {
		file_serialization_proto_rawDescData = protoimpl.X.CompressGZIP(file_serialization_proto_rawDescData)
	})
	return file_serialization_proto_rawDescData
}

var file_serialization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_serialization_proto_goTypes = []interface{}{
	(*Basic)(nil),            // 0: Basic
	(*Basic_Additional)(nil), // 1: Basic.Additional
	nil,                      // 2: Basic.DictEntry
}
var file_serialization_proto_depIdxs = []int32{
	1, // 0: Basic.additional:type_name -> Basic.Additional
	2, // 1: Basic.dict:type_name -> Basic.DictEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_serialization_proto_init() }
func file_serialization_proto_init() {
	if File_serialization_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serialization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Basic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serialization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Basic_Additional); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serialization_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serialization_proto_goTypes,
		DependencyIndexes: file_serialization_proto_depIdxs,
		MessageInfos:      file_serialization_proto_msgTypes,
	}.Build()
	File_serialization_proto = out.File
	file_serialization_proto_rawDesc = nil
	file_serialization_proto_goTypes = nil
	file_serialization_proto_depIdxs = nil
}
